# Site Specific Configuration
name: Silas
description: Collection of stuff
url: https://silasb.me
author: Silas B.
timezone: Australia/Perth

# Keywords
keywords: ['silas', 'blog', 'projects', 'portfolio', 'personal']

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    silent: false

collections:
  Projects:
    output: true

permalink: none

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

